pipeline {
  agent any

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  environment {
    ARTIFACT_ID = "nodeApp:${env.BUILD_NUMBER}"
  }
   stages {
   stage('Building image') {
      steps{
          sh '''
          docker build -t mynodeapp .
             '''  
        }
    }
  
  
    stage('Run tests') {
      steps {
        sh "docker run mynodeapp npm test"
      }
    }
   stage('Deploy Image') {
      steps{
        sh '''
        docker tag mynodeapp 127.0.0.1:5000/nestjsapp:test
        docker push 127.0.0.1:5000/nestjsapp:test   
        '''
        }
      }
    }
}