pipeline {
  agent any

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  environment {
    ARTIFACT_ID = "nodeApp:${env.BUILD_NUMBER}"
  }
   stages {
   stage('Building image') {
      steps{
          sh '''
          docker build -t mynodeapp .
             '''  
        }
    }
  
  
    stage('Run tests') {
      steps {
        sh "docker run mynodeapp npm test"
      }
    }
   stage('Deploy Image') {
      steps{
        sh '''
        echo "admin" | docker login -u "admin" --password-stdin registry.uner.edu.ar 
        docker tag mynodeapp registry.uner.edu.ar:5000/nestjsapp:test
        docker push registry.uner.edu.ar:5000/nestjsapp:test   
        '''
        }
      }
    }
}